### ISSUE TITLE
I suspect you accidently checked in an open or temporary file

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [BestU/STM32_for_Arduino_BSP#1]
https://github.com/BestU/STM32_for_Arduino_BSP/blob/master/stm32/cores/arduino/wiring.h~

**Comment by BestU** [comment]
Thank！ I've removed.

**Comment by rogerclarkmelbourne** [comment]
Now worries

FYI. I have recently fixed some bugs and added a new library, so you may want to set my repo as your update master to get those changes (You will need to look in the Git docs to see precisely how to do this)
